name: Build and Deploy Fraud API

on:
  push:
    branches:
      - main

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --frozen --no-dev

      - name: Run tests
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: uv run pytest tests/test_api.py -v

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image to ACR
        run: |
          az acr build \
            --registry fraudriskregistry \
            --image fraud-api:${{ github.sha }} \
            --file docker/Dockerfile \
            .

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name fraud-api \
            --resource-group shaliq_study \
            --image fraudriskregistry.azurecr.io/fraud-api:${{ github.sha }} \
            --set-env-vars AZURE_STORAGE_CONNECTION_STRING=secretref:azure-storage-connection-string DATABASE_URL=secretref:database-url
